if (FML.isModLoaded("chisel")) {

	NEI.hide("chisel:marble*");
	NEI.hide("chisel:limestone*");
	NEI.hide("chisel:*cobblestone");
	NEI.hide("chisel:glass*");
	NEI.hide("chisel:sandstone");
	NEI.hide("chisel:sandstone2");
	NEI.hide("chisel:sand_snakestone");
	NEI.hide("chisel:sandstone_scribbles");
	NEI.hide("chisel:*_block");
	NEI.hide("chisel:glowstone");
	NEI.hide("chisel:nether*");
	NEI.hide("chisel:stonebricksmooth");
	NEI.hide("chisel:stone_snakestone");
	NEI.hide("chisel:dirt");
	NEI.hide("chisel:ice");
	NEI.hide("chisel:ice_pillar");
	NEI.hide("chisel:ice_stairs.*");
	NEI.hide("chisel:*_planks");
	NEI.hide("chisel:obsidian");
	NEI.hide("chisel:obsidian_snakestone");
	NEI.hide("chisel:iron_bars");
	NEI.hide("chisel:bookshelf");
	NEI.hide("chisel:glass_pane");
	NEI.hide("chisel:mossy_templeblock");
	NEI.hide("chisel:cloud");
	NEI.hide("chisel:stained_glass_*");
	NEI.hide("chisel:leaves");
	NEI.hide("chisel:torch*");
	NEI.hide("chisel:jackolantern*");
	NEI.hide("chisel:brickCustom");
	NEI.hide("chisel:pumpkin*");
	NEI.hide("chisel:arcane");
	NEI.hide("chisel:chest*");
	NEI.hide("chisel:diorite");
	NEI.hide("chisel:packedice_pillar");
	NEI.hide("chisel:packedice_stairs.*");
	NEI.hide("chisel:andesite");
	NEI.hide("chisel:tallow");
	NEI.hide("chisel:marble_pillar_slab_top");
	NEI.hide("chisel:amber");
	NEI.hide("chisel:limestone_slab_top");
	NEI.hide("chisel:marble_slab_top");
	NEI.hide("chisel:packedice");
	NEI.hide("chisel:granite");
	NEI.hide("chisel:thaumium");
	NEI.hide("chisel:bloodRune");
	NEI.hide("chisel:bloodBrick");
	NEI.hide("chisel:tinblock");
	NEI.hide("chisel:leadblock");
	NEI.hide("chisel:bronzeblock");
	NEI.hide("chisel:silverblock");
	NEI.hide("chisel:aluminumblock");
	NEI.hide("chisel:steelblock");
	NEI.hide("chisel:copperblock");
	NEI.hide("chisel:uraniumblock");
	NEI.hide("chisel:factoryblock2");
	NEI.hide("chisel:gold2");
	NEI.hide("chisel:hexLargePlating");
	NEI.hide("chisel:iron2");
	NEI.hide("chisel:rebel");
	NEI.hide("chisel:technical2");
	NEI.hide("chisel:technical3");
	NEI.hide("chisel:technical4");
	NEI.hide("chisel:voidstoneRunic");
	NEI.hide("chisel:futuraCircuit");
	NEI.hide("chisel:aluminum_stairs.*");
	NEI.hide("chisel:end_Stone");
	NEI.hide("chisel:beacon");
//	NEI.hide("");
//	NEI.hide("");
//	NEI.hide("");
	
	NEI.override("chisel:concrete", [0]);
	NEI.override("chisel:road_line", [0]);
	NEI.override("chisel:holystone", [0]);
	NEI.override("chisel:lavastone", [0]);
	NEI.override("chisel:fantasyblock", [0]);
	NEI.override("chisel:carpet_block", [0]);
	NEI.override("chisel:carpet", [0]);
	NEI.override("chisel:tyrian", [0]);
	NEI.override("chisel:templeblock", [0]);
	NEI.override("chisel:factoryblock", [0]);
	NEI.override("chisel:paperwall", [0]);
	NEI.override("chisel:woolen_clay", [0]);
	NEI.override("chisel:laboratoryblock", [0]);
	NEI.override("chisel:voidstone", [0]);
	NEI.override("chisel:waterstone", [0]);
	NEI.override("chisel:fantasyblock2", [0]);
	NEI.override("chisel:warningSign", [0]);
	NEI.override("chisel:technical", [0]);
	NEI.override("chisel:hexPlating", [0]);
	NEI.override("chisel:voidstone2", [0]);
	NEI.override("chisel:grimstone", [0]);
	NEI.override("chisel:technical2", [0]);
	NEI.override("chisel:futura", [0]);
	NEI.override("chisel:antiBlock", [15]);
	NEI.override("chisel:paperwall_block", [0]);
	NEI.override("chisel:present", [0]);
	NEI.override("chisel:nation", [0]);
	NEI.override("chisel:valentines", [0]);
	NEI.override("chisel:purpur", [0]);
//	NEI.override("", [0]);
//	NEI.override("", [0]);
}
